name: syncToGitee
on:
  push:
    branches:
      - gh-pages

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/z-ti'
          dst: 'gitee/flybird-ui'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "fly-ui"
          force_update: true
          debug: true
      
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: huzhifu
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: flybird-ui/fly-ui
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages

      - name: Send dingding ok notify
        if: ${{ success() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          secret: ${{ secrets.DING_SECRET }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "部署状态",
                  "text": "#### ${{ github.ref_name }}分支代码 部署成功 @17600299297 \n > 意气成功日，春风起絮天。 \n > ![screenshot](https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fseopic.699pic.com%2Fphoto%2F50088%2F9764.jpg_wh1200.jpg&refer=http%3A%2F%2Fseopic.699pic.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654021444&t=cdf518cc5f78036d8c900113be6e5db8)\n > ###### 访问地址 [链接](https://z-ti.github.io/fly-ui/) \n"
              },
              "at": {
                  "atMobiles": [
                      "17600299297"
                  ],
                  "atUserIds": [],
                  "isAtAll": false
              }
            }
      
      - name: Send dingding fail notify
        if: ${{ failure() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          secret: ${{ secrets.DING_SECRET }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "部署状态",
                  "text": "#### ${{ github.ref_name }}分支代码 部署失败 @17600299297 \n > 千磨万击还坚劲，任尔东西南北风。 \n > ![screenshot](https://pics3.baidu.com/feed/b999a9014c086e06587499b07945b7f208d1cbc5.jpeg?token=a53a305d267f0de6a749d01e182945d4)\n > ###### 查看错误详情 [链接](https://github.com/z-ti/fly-ui/actions) \n"
              },
              "at": {
                  "atMobiles": [
                      "17600299297"
                  ],
                  "atUserIds": [],
                  "isAtAll": false
              }
            }